# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'CornerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CornerDemo
  pod 'SwiftCharts', '~> 0.6.1'
  pod 'CSV.swift', '~> 2.2.1'
  pod 'FontBlaster'
  pod 'SideMenu'

  target 'CornerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
